In [36]:
#필요한 라이브러리 호출
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
from matplotlib import rc
rc('font', family='AppleGothic')
%matplotlib inline
import seaborn as sns
import pandas_profiling as pp

In [37]:
data = pd.read_excel('마스터.xlsx')

# data['시각화지수'] =  data.좋아요수 +(data.이미지수*10) + (100 - data.비디오수*10)

In [38]:
# data = data[data['달성률']<15000]
data = data[data['이미지수']<80]

In [39]:
data.index = list(range(len(data)))

label = [0,1,2,3,4,]
bins = [0, 15000, 65000, 100000, 500000, 1000000000]
cats = pd.cut(data.일펀딩금액, bins, labels = label)

data['일펀딩_분류'] = cats

In [40]:
# 아래의 데이터들은 하나의 값으로 크게 만든 데이터들이 있음

data = data[(data.리워드종류수!=30) & (data.리워드종류수 !=26) & (data.리워드종류수 !=35) & (data.리워드종류수 !=32) & (data.리워드종류수 !=39) &
            (data.리워드종류수 !=19) & (data.리워드종류수 !=35) & (data.리워드종류수 !=36) & (data.리워드종류수 !=24)]

In [41]:
data.index = list(range(len(data)))

label = [0,1,2,3,4]
bins = [-1, 1, 4, 16,22,10000]
cats = pd.cut(data.리워드종류수, bins, labels = label)

data['리워드종류수_분류'] = cats

In [42]:
data.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'url', '메이커', '펀딩시작날짜', '펀딩마감날짜',
       '펀딩시작요일', '목표금액', '서포터수', '좋아요수', '글업데이트수', '댓글수', '리워드종류수', '이미지수',
       '비디오수', '배송시작날짜', '마감배송차이', '인스타존재여부', '인스타팔로워수', '와디즈팔로워수', '과거프로젝트수',
       '과거성공프로젝트수', '앵콜펀딩여부', '음절수', '단어수', '문장수', 'Strong', 'Under', '가독성',
       '가독성2', '제목단어수', '펀딩성공여부', '달성률', '펀딩시작월', '소비자물가', '근원물가', '생활물가',
       '실질GDP성장률', '제목', '달성액', '요약글', '카테고리', '디자인소품', '반려동물', '뷰티',
       '스포츠·모빌리티', '여행·레저', '테크·가전', '패션·잡화', '푸드', '홈리빙', '분기', '와디즈기사개수',
       '크라우드펀딩기사개수', 'PER', 'PBR', 'ROE', 'EBIT', '페이스북팔로워수', 'sns팔로워수', 'Fri',
       'Mon', 'Sat', 'Sun', 'Thu', 'Tue', 'Wed', '음절수_제목', '단어수_제목', '문장수_제목',
       '가독성_제목', '가독성_제목.1', '펀딩기간', '일펀딩금액', '일글수', '문장당강조', '문장당밑줄', '문장지수',
       '성공비율', '일펀딩_분류', '리워드종류수_분류'],
      dtype='object')

In [43]:
# 필요한 컬럼만 추출

total = data[['목표금액', '리워드종류수', '이미지수', '비디오수', '일펀딩_분류','가독성_제목','가독성_제목.1',
       '마감배송차이', '인스타존재여부', '인스타팔로워수', '와디즈팔로워수', '과거프로젝트수','과거성공프로젝트수','리워드종류수_분류',
       '앵콜펀딩여부', '음절수', '단어수', '문장수', 'Strong', 'Under', '가독성', '가독성2', 'sns팔로워수','페이스북팔로워수',
       '제목단어수', '달성률', '디자인소품', '반려동물', '뷰티', '스포츠·모빌리티', '여행·레저','글업데이트수',
       '테크·가전', '패션·잡화', '푸드', '홈리빙', 'Fri', 'Mon', 'Sat', 'Sun', 'Thu', 'Tue', 'Wed',
       '음절수_제목', '단어수_제목', '문장수_제목',  '펀딩기간', '일펀딩금액','크라우드펀딩기사개수','소비자물가',
       '일글수', '문장당강조', '문장당밑줄', '문장지수', '성공비율']]

In [44]:
from sklearn import preprocessing 

label_encoder = preprocessing.LabelEncoder()
total.리워드종류수_분류 = label_encoder.fit_transform(total.리워드종류수_분류) 
total.일펀딩_분류 = label_encoder.fit_transform(total.일펀딩_분류) 

/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5096: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [60]:
# 달성률 범주생성
# 현재 범주는 임의의 범주이며
# 여러가지 시도하면서 정확도를 봐야할듯

total.index = list(range(len(total)))
total_target = total

target_list = []

for i in range(len(total_target)):
    if total_target.달성률[i] < 100:
        target_list.append(0)

    elif total_target.달성률[i] < 850:
        target_list.append(1) 
    
    else:
        target_list.append(2)
    
total_target['타겟'] = target_list
total_data = total_target.drop(columns = ['달성률'])
total_target.pivot_table(index = '타겟', aggfunc = 'count', values = '달성률')

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


달성률
타겟      
0   1098
1   2726
2   1244

In [61]:
import sklearn.metrics as mt

def get_clf_eval(y_test, y_pred):
    matrix = mt.confusion_matrix(y_test, y_pred)
    accuracy = mt.accuracy_score(y_test, y_pred)
    precision = mt.precision_score(y_test, y_pred,average='weighted')
    recall = mt.recall_score(y_test, y_pred, average = 'weighted')
    f1 = mt.f1_score(y_test,y_pred, average='weighted')

    print('오차행렬')
    print(matrix)
    print('accuracy:',accuracy)
    print('precision:',precision)
    print('recall:',recall)
    print('f1:',f1)   

In [62]:
X = total_data.drop(columns=['타겟'])
y = total_data.타겟

# 학습용/테스트용 데이터 분리

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=33)

In [64]:
import sklearn.linear_model as lm

logr = lm.LogisticRegression(multi_class="multinomial",solver="lbfgs")

reg = logr.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [65]:
train_score = reg.score(X_train, y_train)
test_score = reg.score(X_test, y_test)

y_pred = reg.predict(X_test)

get_clf_eval(y_test, y_pred)

오차행렬
[[ 34 273   0]
 [ 20 815   0]
 [  2 377   0]]
accuracy: 0.5581854043392505
precision: 0.42795203250703384
recall: 0.5581854043392505
f1: 0.42687081619887945


/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
